spring:
  application:
    name: mc-eureka-server-01
server:
  port: 9527

# eureka server 配置
eureka:
  instance:
    # eureka server 端名称
    hostname: mcloud-eureka-server-01
  client:
    # 是否向 eureka 注册中心注册本服务 （false 不注册， 本身作为服务端 不需要注册）
    register-with-eureka: false
    # 是否检索服务 （作为服务端，本身是注册中心 只需要维护 各 provider 服务实例 不需要去检索服务）
    fetch-registry: false
    service-url:
      # 设置 与 eureka server 交互的地址， 查询服务  和  注册服务 使用到
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      # 集群
      defaultZone: http://mcloud-eureka-server-02:9528/eureka/,http://mcloud-eureka-server-03:9529/eureka/
