server:
  port: 10086

spring:
  application:
    name: users
  # mysql 连接信息
  datasource:
    url: jdbc:mysql://114.116.138.225:3306/anm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cdwzit2019##
    hikari:
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 3
  # jpa信息
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL55Dialect
    show-sql: true
    hibernate:
      ddl-auto: update