server:
  port: 80


spring:
  application:
    name: gateway-server

  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
          # 开启 从注册中心 动态创建路由功能
          enabled: true
      routes: #配置路由
        - id: member
          uri: lb://member-server
          predicates:
            - Path=/member/**
          filters:
            - StripPrefix=1

        - id: oauth
          uri: lb://oauth-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1


  security:
    oauth2:
      resourceserver:
        jwt:
          # 配置 rsa 公钥访问地址 (系统内部使用)
          jwk-set-uri: "http://127.0.0.1:11111/api/rsa/publickey"


  redis:
    database: 1
    port: 6379
    host: 127.0.0.1


# 自定义 配置 uri 白名单
security:
  ignore:
    uris:
      - "/actuator/**"
      - "/auth/oauth/token"
      - "/auth/api/rsa/publickey"
