server:
  port: 11111


spring:
  application:
    name: oauth-server



  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



  redis:
    database: 1
    port: 6379
    host: 127.0.0.1
    password:


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/whiplash-oauth?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 2


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update






management:
  endpoints:
    web:
      exposure:
        include: "*"
