server:
  port: 11111


spring:
  application:
    name: oauth-server



  cloud:
    nacos:
      discovery:
        server-addr: 120.25.216.73:8848



  redis:
    database: 1
    port: 6379
    host: 120.25.216.73
    password: redis


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


  datasource:
    url: jdbc:mysql://120.25.216.73:3306/whiplash-oauth?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: ENC(UUcDXrhTzvXcjc7ypW/mqQ==)
    password: ENC(guYfbOLDOjbIP974BnUaSnsEmlzkWc1o)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 2


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update






management:
  endpoints:
    web:
      exposure:
        include: "*"


jasypt:
  encryptor:
    # 盐
    password: whiplash
    # 算法
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
