server:
  port: 80

spring:
  application:
    name: nimbusjwt

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nimbus-jwt?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 50
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update



