server:
  port: 10087

spring:
  application:
    name: users
  # mysql 连接信息
  datasource:
    url: jdbc:mysql://114.116.138.225:3306/anm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cdwzit2019##
    hikari:
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 3
  # jpa信息
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL55Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

# 配置 eureka 客户端 注册到 服务端的 地址
eureka:
  client:
    service-url:
      defaultZone: http://mcloud-eureka-server-02:9528/eureka/,http://mcloud-eureka-server-01:9527/eureka/,http://mcloud-eureka-server-03:9529/eureka/
  instance:
    instance-id: users-10087
    prefer-ip-address: true
info:
  app.name: mcloud-service-users-02
  app.author: vostroi
  app.desc: for test
  build.artifactId: users
  build.groupId: com.vostroi

