server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    # 注册中心配置
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        enabled: true
    # 网关配置
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms_cust
          uri: lb://service-customer
          predicates:
            ## 不能写多个 Path
            - Path=/cust/mbl/**,/cust/pad/**
#            - Method=GET,POST
#            - Before=2021-05-09T09:11:27.551+08:00[Asia/Shanghai]   #3.在某个时间点之前--》》可以匹配访问（ZonedDateTime格式）
#            - After=2021-04-09T09:11:27.551+08:00[Asia/Shanghai]    #4.在某个时间点之后--》》可以匹配访问
#            - Between=2021-04-09T09:11:27.551+08:00[Asia/Shanghai],2021-05-09T09:11:27.551+08:00[Asia/Shanghai] #5.同上，时间点之间
#            - Header=X-Header-Token,token   #6.根据header中的信息匹配--》》提供两个值name，value（正则）两个值必须均匹配

        - id: ms_prd
          uri: lb://service-product
          predicates:
            - Path=/prd/mbl/**
        - id: hystrix
          uri: lb://hystrix_watcher
          predicates:
            - Path=/hystrix/**


# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: debug



