server:
  port: 8080

spring:
  application:
    name: consumer

info:
  app.name: mcloud-service-consumer
  app.author: vostroi
  build.artifactId: users
  build.groupId: com.vostroi


eureka:
  client:
    service-url:
      defaultZone: http://mcloud-eureka-server-03:9529/eureka/,http://mcloud-eureka-server-02:9528/eureka/,http://mcloud-eureka-server-01:9527/eureka/
  instance:
    instance-id: consumer-8080
    prefer-ip-address: true

